<?php include_once"header.php"?>
 <!-- Breadcroumbs start -->
  <div class="wshipping-content-block wshipping-breadcroumb inner-bg-1">
    <div class="container">
      <div class="row">
         <div class="col-12 col-lg-7">
            <h1>Terms and Conditions</h1>
            <a href="index.php" title="Home">Home</a> / Terms and Conditions 
         </div>
         <div class="col-12 col-lg-5 text-right"><h4>Galaxy Staffing  <br>We Pride in <span>Excellent Care </span> </h4></div>
      </div>
    </div>
  </div>
  <!-- Breadcroumbs end -->
  
  <!-- About content start -->  
  <div class="wshipping-content-block" style="padding-bottom: 50px;">
    <div class="container">
      <div class="row flex-lg-row-reverse">
         <div class="col-12 col-lg-12">
            <div class="right-block">

<h2 class="text-uppercase">Terms and Conditions for Website Usage</h2>
<p style="text-align:justify;">This web site (this "Site") is provided by Galaxy ("Galaxy"), conditional on your acceptance of the terms and conditions of use set forth below (the "Terms and Conditions"). By accessing, using, and/or downloading messages, information, data, text, software or images, or other materials from this Site (the "Materials"), and by sending messages, information, data, text, software or images, or other materials to the Site ("Content"), you agree on your own behalf and on behalf of any entity on whose behalf you may act to accept and abide by these Terms and Conditions for each use and each visit of this Site. If you do not agree to abide by these Terms and Conditions, you should not use this Site or download or use Materials from it. These Terms and Conditions apply exclusively to your access to and use of this Site and do not alter the terms or conditions of any other agreement you may have with Galaxy. In case of inconsistency between these Terms and Conditions and any other agreement you may have with Galaxy, the other agreement shall prevail, but only to the extent of the inconsistency.</p><br>

<h2 class="text-uppercase">1. Changes to Terms and Conditions</h2>

<p style="text-align:justify;">Galaxy has the right, in its sole discretion, to add to, remove, modify or otherwise change any part of these Terms and Conditions, including the <a style="color:#a31414;font-weight:700;" href="privacy_policy.php">Privacy Policy</a> in whole or in part, at any time. Changes will be effective when notice of such change is posted at this Site. Please check these Terms and Conditions frequently for updates by checking the date of "Last Update" at the top of this document. If any change is not acceptable to you, you must discontinue your use of this Site immediately. Your continued use of this Site or downloading or use of Materials from it after any such changes are posted will constitute acceptance of those changes.</p>

<h2 class="text-uppercase">2. Changes to this Site</h2>

<p style="text-align:justify;">Galaxy may terminate, change, suspend or discontinue any aspect of this Site, including (i) changing the availability of any features, at any time without notice or liability; (ii) removing, adding, modifying or otherwise changing any Materials on or from this Site; or (iii) imposing limits on certain features and Services or restricting your access to parts or all of this Site without notice or liability for any reason whatsoever. Galaxy reserves the right but not the duty, in its sole discretion, to correct any errors or omissions in any portion of this Site at any time without notice.</p>
<h2 class="text-uppercase">3. Permitted and Prohibited Uses</h2>
<p style="text-align:justify;">
The Site may be used only for lawful purposes by individuals seeking employment and career information ("Candidates"). You agree to use the Site only to send Content and receive Materials that are proper and related to purpose of the Site.<br>
Subject to these Terms and Conditions, Galaxy grants you a non-exclusive, non-transferable, limited right to access, use and view this Site and the Materials thereon, solely for your own personal or internal company use, provided, however, that you may not, nor may you allow others to, directly or indirectly: (i) remove, from any copy of the Materials downloaded, the copyright or other proprietary notices contained in the Materials; (ii) sell, reproduce, modify or attempt to modify the Materials in any way or reproduce or publicly display, perform, or distribute or otherwise use them for any public or commercial purpose, including without limitation use of the Materials on any other web site; (iii) transfer the Materials to any other person without the written consent of Galaxy; (iv) print or copy any of the HTML or other computer programs that are accessible at this Site; (v) use this Site in any manner that could damage, disable, overburden or impair this Site; (vi) interfere with the security of, or otherwise abuse, this Site or any services, system resources, accounts, servers or networks connected to or accessible through this Site or affiliated or linked sites; (vii) disrupt or interfere with any other person's use or enjoyment of this Site or affiliated or linked sites; (viii) upload, post or otherwise transmit on this Site any Content that would negatively affect the functioning of the Site, including without limitation computer viruses, Trojan horses, worms or other harmful, disruptive or destructive files or computer programs or that imposes an unreasonable or disproportionately large load on this Site's infrastructure; (ix) use any robot, spider or other automatic program or device, or manual process to monitor, copy, summarize, or otherwise extract information from this Site or the Materials in whole or in part; (x) use or attempt to use another's account, password, service, system or other information without prior written authorization from Galaxy; (xi) create or use a false identity on this Site; (xii) attempt to obtain unauthorized access to this Site or portions of this Site that are restricted from general access; (xiii) transmit on, to or from this Site spam, chain letters, junk mail or any other type of unsolicited mass e-mail; (xiv) harvest or otherwise collect information about others, except for the sole stated purposes provided by this Site, including e-mail addresses, without their consent; or (xv) register an e-mail address that you do not own or for which you do not have the express permission of the owner to register.<br><br>
You may post certain Content to the Site. You may only post Content for the lawful, stated purposes of this Site. You agree, that in posting Content, you will not, nor will you allow others to, directly or indirectly: (i) post any incomplete, false or inaccurate biographical information or information which is not your own accurate resume; (ii) post any franchise, pyramid scheme, multi-level marketing (MLM) opportunity, "club membership", distributorship or sales representative agency arrangement or other business opportunity which requires an up front or periodic payment, requires recruitment of other members, sub-distributors or sub-agents; (iii) delete or revise any material posted by any other person or entity; (iv) post or transmit any Content that is unlawful, harmful, threatening, abusive, harassing, defamatory, libelous, vulgar, obscene, or tortuous or materials which infringe or violate any third party's copyright, trademark, trade secrets, privacy or other proprietary or property right or that could constitute a criminal offence, give rise to civil liability or otherwise violate any applicable law; (v) impersonate any person or entity, including without limitation an Galaxy employee or agent, an authorized user of Galaxy' Services, a Candidate, an Employer or a Recruiter, or otherwise misrepresenting your affiliation with any person or entity; (vi) post opinions, notices or advertisements, commercial or otherwise or solicit business from Recruiters who post on the Site, including any solicitation by any of our competitors of Recruiters who post on the Site.<br><br>
In addition, you agree that you are solely responsible for actions and communications undertaken or transmitted in the course of your usage of this Site, and that you will comply with all laws that apply or may apply to your use of or activities on this Site or in respect of the Content and Materials. Galaxy will investigate occurrences which may involve such violations and may involve, and cooperate with, law enforcement authorities in prosecuting users who are involved in such violations.<br><br>
Galaxy reserves the right at all times to disclose any Content provided by you as necessary to satisfy any law, regulation or governmental request, or to edit, refuse to post or remove any Content, in whole or in part, that in Galaxys sole discretion is objectionable or in violation of these Terms and Conditions.
</p>
<h2 class="text-uppercase">4. Registration and Password</h2>
<p style="text-align:justify;">You are responsible for maintaining the confidentiality of your registration information and password. You shall be responsible for all uses of your registration, whether or not authorized by you. You agree to immediately notify Galaxy of any unauthorized use of your registration or password.</p>
<h2 class="text-uppercase">5. Proprietary Rights</h2>
<p style="text-align:justify;">Limited License and Copyright. This Site, including all Materials, is protected by UK and worldwide copyright laws and treaty provisions. You agree to comply with all copyright laws worldwide in your use of this Site and to prevent any unauthorized copying of the Materials. Except as expressly provided herein, Galaxy does not grant any express or implied right or license to you under any intellectual property right, including under any patent, trademark, copyright, trade secret, or confidential information, of Galaxy.<br><br>
Trademarks. The Services names, company names and logos used on this Site may be trademarks, including registered trademarks of Galaxy. Such Services names, company names and logos of Galaxy may not be copied, imitated or used, in whole or in part, without the prior written consent of Galaxy. Other services and company names mentioned on this Site may be the trademarks of their respective owners.<br><br>
Reservation of Rights. Galaxys Services, methods and processes may be covered by one or more patents or other statutory intellectual property rights, and are subject to trade secret and other proprietary rights. Galaxy reserves all such rights.<br><br>
Software. Any software, including calculator software, as well any files, images generated by such software, code and data accompanying such software (the "Software"), used or accessible through this Site is the copyrighted work of Galaxy or its licensors. Unless provided for elsewhere, you are licensed to use the Software on a non-exclusive basis for the purposes expressly stated on this Site. Except as permitted by law, you may not use the Software for any other purpose or attempt to decipher, decompile, disassemble or reverse engineer any of the Software comprising or in any way making up a part of the Site.
</p>
<h2 class="text-uppercase">6. Links and Third Party Content</h2>
<p style="text-align:justify;">Certain links on this Site may take you to other web sites. Galaxy provides these links only as a convenience. These linked sites are not necessarily under the control of Galaxy. If you use these sites, you will leave this Site. If you decide to visit any linked site, you do so at your own risk and it is your responsibility to take all protective measures to guard against viruses and other destructive elements.
Galaxy is not responsible for the contents of any such linked page or any other page not under its control. Galaxy makes no representation or warranty regarding, and does not endorse, any linked web sites, the information appearing thereon or any of the products or services described. Links do not imply that Galaxy sponsors, endorses, is affiliated or associated with, or is legally authorized to use any trademark, trade name, logo or copyright symbol displayed in or accessible through the links, or that any linked site is authorized to use any trademark, trade name, logo or copyright symbol of Galaxy.
</p>
<h2 class="text-uppercase">7. Agreement to <a style="color:#a31414;" href="privacy_policy.php">Privacy Policy</a></h2>
<p style="text-align:justify;">You agree to abide by Galaxys <a style="color:#a31414;font-weight:700;" href="privacy_policy.php">Privacy Policy</a>, which is incorporated by reference into these Terms and Conditions.</p>
<h2 class="text-uppercase">8. Disclaimers</h2>
<p style="text-align:justify;">You acknowledge that any use of or reliance on this Site or any Materials shall be at your sole risk. Galaxy makes no representation or guarantee of any kind regarding the Site and/or the Materials, including with respect to the information provided by third party legal and other consultants, all of which are provided on an "AS IS" basis. Galaxy expressly disclaims all representations, warranties and conditions, including without limitation any implied warranties and conditions of merchantability, merchantable quality, non-infringement and fitness for a particular purpose and those arising by statute or otherwise in law or from a course of dealing or usage of trade. Galaxy does not guarantee that this site will continue to operate, operate without interruptions or that it will be error-free.<br><br>
Not limiting the generality of the foregoing, the information provided on this Site is for general informational purposes only. Information provided on the Site with a byline, identification of publication source, or any other sort of third-party identifier, is provided by third parties on an "As Is" basis, and Galaxy does not review it. Galaxy and its third party consultants do not warrant or guarantee the truth, accuracy or completeness of this information. This Site acts as a venue, among other things, for Recruiters to post job opportunities and Candidates to post CVs.<br><br>
Galaxy does not screen or censor the listings offered. As a result, Galaxy has no control over the quality, safety or legality of the jobs or CVs posted, the truth or accuracy of the listings, the ability of Employers to offer job opportunities to Candidates or the ability of Candidates to fill job openings. In addition, there may be risks, including but not limited to risk of physical harm of dealing with strangers, foreign nationals, underage persons or people acting under false pretenses. You assume all risks associated with dealing with other users with whom you come in contact through the Site.<br><br>
Because user authentication on the Internet is difficult, Galaxy cannot and does not confirm that each user is who they claim to be. Because we do not and cannot be involved in user-to-user dealings or control the behaviour of participants on this Site, in the event that you have a dispute with one or more users, you release Galaxy (and our agents and employees) from all claims, demands and damages of every kind and nature, known and unknown, suspected and unsuspected, disclosed and undisclosed, arising out of or in any way connected with such disputes.<br><br>
Galaxy is under no legal obligation to, and generally does not, control the Content provided by other users which is made available through the Site. By its very nature, other people's information may be offensive, harmful or inaccurate, and in some cases will be mislabelled or deceptively labelled. Galaxy does not guarantee, and makes no representations or warranties as to the truthfulness, accuracy, reliability, currency, veracity or completeness of the Materials or about the results to be obtained using the Materials. The use of the Site and the Material is at your own risk. Changes are periodically made to the Site and may be made at any time.<br><br>
This Site contains materials, data, information provided, posted or offered by third parties, including third party provided content, advertisements and user content. You agree that Galaxy shall have no liability whatsoever for any such third party material, data or information.<br><br>
You acknowledge and agree that you are solely responsible for the form, content and accuracy of any resume, posting or other Content placed by you, as applicable on the Site.<br><br>
Galaxy shall not be responsible for any employment decisions, for whatever reason made, made by any entity posting jobs on the Site.
</p>
<h2 class="text-uppercase">9. Limitation of Liability</h2>
<p style="text-align:justify;">You agree that Galaxy and any third party mentioned on this site will not be responsible or liable for any loss or damages whatsoever, including without limitation indirect, special or consequential damages or other damages (including without limitation damages for harm to business, loss of information or programs or data, loss of profit, loss of savings, loss of revenue), arising from or in connection with the use of or access to, or the inability to use or access, this site, the materials, any content provided or any linked website of a third party, even if Galaxy, or such a third party has been advised of the possibility of such damage or loss. In any event, you agree that Galaxy's aggregate liability for damages shall be limited to £100.<br><br>
The limitations of liability and disclaimers in these Terms and Conditions apply regardless of the form of action, whether in contract, warranty, civil liability, delict, quasi-delict, strict liability, negligence, or other tort and shall survive a fundamental breach or breaches, or the failure of the essential purpose of contract or the failure of an exclusive remedy.
</p>
<h2 class="text-uppercase">10. Indemnity</h2>
<p style="text-align:justify;">You agree to defend, indemnify and hold harmless each of Galaxy, its affiliates, and each of their officers, directors, employees and agents, including all third parties mentioned at the Site, from and against any and all claims, actions or demands, including without limitation reasonable legal and accounting fees, alleging or resulting from your use of the Site and the Materials or your breach of these Terms and Conditions.</p>
<h2 class="text-uppercase">11. Choice of law</h2>
<p style="text-align:justify;">This Site is controlled, operated and administered by Galaxy from its offices within UK. Galaxy makes no representation or warranty that materials at this Site are appropriate or available for use at any locations outside the UK. If you access this Site from outside the UK, you are responsible for compliance with all local law. You may not export any of the Materials accessible through this Site in violation of applicable export laws and regulations. These Terms and Conditions shall be interpreted, construed and governed by the laws in force in England & Wales, without reference to its conflict of laws principles, except where prohibited by mandatory provisions of the laws applicable in your jurisdiction. Except in respect of any matter relating to the enforcement of intellectual property rights and protection of confidential information, the parties agree that any action, suit or proceeding arising out of or related to these Terms and Conditions shall be commenced in England. Each party hereby agrees to submit to the jurisdiction of the courts of England & Wales and to waive any objections based upon venue in any such action, suit or proceeding. The United Nations Convention on Contracts for the International Sale of Goods does not apply to these Terms and Conditions.</p>
<h2 class="text-uppercase">12. Arbitration</h2>
<p style="text-align:justify;">Any and all disputes arising out of these Terms and Conditions, its performance, breach, enforcement, existence or validity, including any failure of the parties to reach agreement with respect to matters provided for in these Terms and Conditions and all matters of dispute relating to the rights and obligations of the parties, which cannot be amicably resolved, even if only one of the parties declares that there is a difference, will be referred to and finally settled by private and confidential binding arbitration before a single arbitrator held in England, in English and governed by the laws of England & Wales. The arbitrator shall be a person who is legally trained and who has experience in the information technology field in the UK and is independent of either party.<br><br>
Notwithstanding the foregoing, each party may pursue the protection intellectual property rights and confidential information through injunctive or other equitable relief through the courts.
</p>
<h2 class="text-uppercase">13. General</h2>
<p style="text-align:justify;">(i) Except as expressly provided in additional terms of use for areas of the Site, a particular legal notice, or an additional Agreement, these Terms and Conditions constitute the entire agreement between Galaxy and you with respect to the subject matter hereof; (ii) Any cause of action you may have with respect to your use of this Site or which is the subject of these Terms and Conditions must be commenced within one (1) year after the claim or cause of action arises; (iii) If for any reason a court of competent jurisdiction finds any provision of these Terms and Conditions or portion thereof to be unenforceable, that provision shall be enforced to the maximum extent permissible so as to effect the intent of these Terms and Conditions, and the remainder of these Terms and Conditions shall continue in full force and effect; (iv) The relationship of the parties is solely that of independent contractors and neither party shall have any authority to act for or bind the other party; (v) The waiver of any breach or default hereunder shall not constitute the waiver of any other or subsequent breach or default; (vi) No changes to these Terms and Conditions shall be made except by a revised posting on this page.</p>
<h2 class="text-uppercase">14. Additional Terms of Use.</h2>
<p style="text-align:justify;">Certain areas of this Site may be subject to additional terms of use. By using such areas, or any part thereof, you agree to be bound by the additional terms of use applicable to such areas.</p>


            </div>   
         </div>
      </div>
    </div>
  </div>
  <!-- About content end -->



  <!-- Footer start -->
<?php include_once"footer.php"?>